import os
env = Environment(
    ENV=os.environ,
    CXXFLAGS=['-std=c++11'],
    CPPPATH=['/opt/local/include'],
    LIBPATH=['/opt/local/lib'],
    LIBS=['sndfile', 'lo'],
    )

testenv = env
testenv.Append(LIBS=['gtest'])
testenv.Program('tests', Glob('*.cc') + Glob('test/*.cc'))

# vim: ft=python
